name: weather_app
description: A Flutter weather application using Riverpod for state management and API integration.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/1.png
    - assets/11.png
    - assets/12.png
    - assets/13.png
    - assets/14.png